export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CANCEL_CHECKOUT = 'CANCEL_CHECKOUT';
export const CONTINUE_CHECKOUT = 'CONTINUE_CHECKOUT';